meta_product_name: "Talent Protocol"
meta_title: "Talent Protocol - Beta Dapp"
meta_description: "Talent Protocol is the web3 professional network where high-potential individuals can build an on-chain resume and launch a talent token, allowing anyone to easily invest in their careers."
meta_image: "/metaimage.jpeg"
meta_card_type: "summary_large_image"
